projects:
  nipplio:
    schemaPath: amplify/backend/api/nipplio/build/schema.graphql
    includes:
      - ../app/src/graphql/**/*.js
    excludes:
      - ./amplify/**
    extensions:
      amplify:
        codeGenTarget: javascript
        generatedFileName: ''
        docsFilePath: ../app/src/graphql
        region: eu-west-1
        apiId: null
        maxDepth: 2
extensions:
  amplify:
    version: 3
