/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_cognito_identity_pool_id": "eu-west-1:ab6c5fb3-5fb4-438c-a922-9754defbd093",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_siyCZNz5T",
    "aws_user_pools_web_client_id": "5ujipjg5g58g7fcmjcl1o43jvj",
    "oauth": {},
    "aws_appsync_graphqlEndpoint": "https://yfcfk4welfeydecbzrhxzielly.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "AMAZON_COGNITO_USER_POOLS",
    "aws_cloud_logic_custom": [
        {
            "name": "getIdentityId",
            "endpoint": "https://hb1c7aykgl.execute-api.eu-west-1.amazonaws.com/staging",
            "region": "eu-west-1"
        }
    ],
    "aws_user_files_s3_bucket": "nippliosoundbucket84647-staging",
    "aws_user_files_s3_bucket_region": "eu-west-1"
};


export default awsmobile;
