# Build/release
name: Build/release
on: workflow_dispatch
jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v4
        with:
          node-version: 22
      - run: cd app && npm ci
      - run: cd app && npm run electron:build
      - name: Build/release Electron app
        uses: lucienkerl/action-electron-builder@master
        env:
          CSC_KEY_PASSWORD: ${{ secrets.MAC_CERTS_PASSWORD }}
          CSC_LINK: ${{ secrets.MAC_CERTS }}
        with:
          package_root: './app/'
          build_script_name: 'electron:build'
          use_vue_cli: false
          skip_build: true
          github_token: ${{ secrets.github_token }}
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}